name:                adventofcode
version:             0.1.0.0
homepage:            https://github.com/oshyshko/adventofcode
license:             BSD3
license-file:        LICENSE
author:              Oleksandr Shyshko
maintainer:          oshyshko@gmail.com
copyright:           Oleksandr Shyshko

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

ghc-options:
- -Wall
- -fno-warn-unused-do-bind
- -O2
- -optc-O3
# Note: adding flags for extensions like -XLambdaCase breaks `stack test` and Atom (ghcmod)

library:
  source-dirs: src
  dependencies:
  - hspec
  - base
  - aeson
  - array
  - bytestring
  - containers
  - deepseq
  - hashable
  - lens
  - mtl
  - parsec
  - pureMD5
  - scientific
  - split
  - time
  - unordered-containers

executables:
  adventofcode-exe:
    main: MainExe.hs
    source-dirs: src.exe
    dependencies:
    - base
    - adventofcode

tests:
  adventofcode-test:
    main: MainTest.hs
    source-dirs: test
    dependencies:
    - base
    - adventofcode
    - hspec
