name:                adventofcode
version:             0.1.0.0
homepage:            https://github.com/oshyshko/adventofcode
license:             BSD3
license-file:        LICENSE
author:              Oleksandr Shyshko
maintainer:          oshyshko@gmail.com
copyright:           Oleksandr Shyshko

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

ghc-options:
- -Wall
- -fno-warn-unused-do-bind
- -O2
- -optc-O3
#  from https://kowainik.github.io/posts/2019-02-06-style-guide#general-recommendations
- -Wcompat
- -Widentities
# - -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
# - -Wmissing-export-lists
# - -Wmissing-deriving-strategies   <--  8.8.1
- -fhide-source-paths
- -freverse-errors

default-extensions:
- DeriveGeneric
- FlexibleContexts
- LambdaCase
- MultiWayIf
- OverloadedStrings
- ScopedTypeVariables
- StrictData

library:
  source-dirs: src
  dependencies:
  - base
  - aeson
  - array
  - bytestring
  - containers
  - deepseq
  - hashable
  - hspec
  - lens
  - mtl
  - parsec
  - pureMD5
  - scientific
  - split
  - time
  - unordered-containers

executables:
  adventofcode-exe:
    main: MainExe.hs
    source-dirs: src.exe
    dependencies:
    - adventofcode
    - base
    - bytestring
    - byteunits
    - containers
    - process
    - split
    ghc-options:
    - -rtsopts

tests:
  adventofcode-test:
    main: MainTest.hs
    source-dirs: test
    dependencies:
    - base
    - adventofcode
    - hspec
