name:                adventofcode
version:             0.1.0.0
github:              "oshyshko/adventofcode"
license:             BSD3
license-file:        LICENSE
author:              Alex Shyshko
maintainer:          oshyshko@gmail.com
copyright:           Alex Shyshko

library:
  source-dirs: src
  dependencies:
  - aeson
  - ansi-terminal
  - arithmoi
  - array
  - base
  - bitvec
  - bytestring
  - combinatorial
  - containers
  - cryptohash-md5
  - deepseq
  - directory
  - exceptions
  - filepath
  - ghc-compact
  - hashable
  - hspec # needed to make Atom happy
  - mtl
  - parsec
  - primitive
  - psqueues
  - safe-exceptions
  - scientific
  - split
  - strict-tuple
  - string-qq
  - time
  - unordered-containers
  - vector
  - vector-th-unbox

executables:
  adventofcode-exe:
    main: MainExe.hs
    source-dirs: src.exe
    dependencies:
    - adventofcode
    - base
    - bytestring
    - containers
    - directory
    - filepath
    - process
    - split
    - template-haskell
    ghc-options:
    - -rtsopts

tests:
  spec:
    main: MainTest.hs
    source-dirs: test
    dependencies:
    - base
    - adventofcode
    - containers
    - hspec
    - string-qq
    - vector
    ghc-options:
    - -rtsopts

# dependencies:
# - haskell-stack-trace-plugin

ghc-options:
# enable stack traces: uncomment 2 lines, comment 1 line
# - -fplugin=StackTrace.Plugin
# - -Wno-redundant-constraints
- -Wredundant-constraints

- -Wall
- -Werror=missing-methods
- -Werror=type-defaults
- -Werror=incomplete-patterns
- -fno-warn-unused-do-bind
- -O2
# - -fllvm

#  from https://kowainik.github.io/posts/2019-02-06-style-guide#general-recommendations
- -Widentities
# - -Wincomplete-uni-patterns
- -Wincomplete-record-updates
# - -Wmissing-export-lists
# - -Wmissing-deriving-strategies   <--  8.8.1
# exclude these for etlas:
- -Wcompat
- -Wpartial-fields
- -fhide-source-paths
- -freverse-errors
# stan
#- -fwrite-ide-info
#- -hiedir=.hie

default-extensions:
- AllowAmbiguousTypes
- BangPatterns
- BinaryLiterals
- BlockArguments
- ConstraintKinds
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GADTs
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns
