name: ci

on:
    pull_request:
    push:

jobs:
    stack:
        name: ${{ matrix.os }}, ${{ matrix.resolver }}, ${{ matrix.ghc }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [macOS-latest, ubuntu-latest, windows-latest]
                resolver: [lts-18.19]
                stack: ['2.7.3']
                ghc: ['8.10.7', '9.2.1']

        env:
            STACK     : stack --resolver ${{ matrix.resolver }} --compiler ${{ matrix.ghc }}
            CACHE_DIR : ${{ matrix.os == 'windows-latest' && '~/AppData/Roaming/stack' || '~/.stack' }}
            BINARY    : ./dist/adventofcode-exe${{ matrix.os == 'windows-latest' && '.exe' || '' }}

        steps:
        - uses: actions/checkout@v2

        - name: Install stack
          uses: haskell/actions/setup@v1
          with:
              stack-version: ${{ matrix.stack }}
              ghc-version: ${{ matrix.ghc }}
              enable-stack: true
              stack-no-global: true

        - name: Cache ${{ env.CACHE_DIR }}
          uses: actions/cache@v2.1.3
          with:
              path: ${{ env.CACHE_DIR }}
              key: ${{ runner.os }}-${{ matrix.resolver }}-${{ matrix.ghc }}

        - name: Clean
          run: ${{ env.STACK }} clean

        - name: Clean ~/.stack/setup-exe-* (skip for Windows)
          if: ${{ runner.os != 'Windows' }}
          run: rm -rf ~/.stack/setup-exe-cache && rm -rf ~/.stack/setup-exe-src

        - name: Install GHC and deps
          run: ${{ env.STACK }} build --only-dependencies

        - name: Build
          run: |
              mkdir ./dist
              ${{ env.STACK }} install --test --bench --no-run-tests --no-run-benchmarks --copy-bins --local-bin-path ./dist

        - name: Test
          run: ${{ env.STACK }} test

        - name: Run
          run: ${{ env.BINARY }}

        - name: Install hlint
          run: ${{ env.STACK }} install hlint

        - name: Run hlint
          run: ${{ env.STACK }} exec hlint -- src src.exe test --no-exit-code

        - name: List packages
          run: ${{ env.STACK }} exec ghc-pkg list || true

        - name: Compress binary
          uses: svenstaro/upx-action@v2
          with:
              file: ${{ env.BINARY }}
              strip: true
              args: --ultra-brute
